baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
title = "主公的工程日志"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  math = true



[params.profileMode]
  enabled = true
  title = "主公的工程日志"
  subtitle = "控制 · 嵌入式 · 系统思考"
  imageUrl = ""
  imageTitle = ""
  imageWidth = 120
  imageHeight = 120
  buttons = [
    { name = "Control", url = "/control/" },
    { name = "Embedded", url = "/embedded/" },
    { name = "Math", url = "/math/" },
    { name = "Thinking", url = "/thinking/" }
  ]

[menu]

  [[menu.main]]
    name = "Control"
    url = "/control/"
    weight = 1

  [[menu.main]]
    name = "Embedded"
    url = "/embedded/"
    weight = 2

  [[menu.main]]
    name = "Math"
    url = "/math/"
    weight = 3

  [[menu.main]]
    name = "Thinking"
    url = "/thinking/"
    weight = 4

